spring.application.name=api-prueba-tecnica
server.port=3200

#Reemplazar variables por las de conexion a base de datos
#reemplaza nombre usuario y contraseña
#reemplazar puerto y host para la conexion a la base de datos
#unicamente debe de existir la base de datos con el nombre prueba-tecnica
spring.datasource.url=jdbc:postgresql://localhost:5435/prueba-tecnica
spring.datasource.username=postgres
spring.datasource.password=root-admin
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

logging.level.org.hibernate.sql=debug
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.lob.non_contextual_creation=true

jwt.secret.key=mGyYSQcsIZWt5EHSqohBWzPDtKqNNgop3qsCt0R8/s8tHTtpSxUD5vo1KPQXezn0Q4t2+iuRzx7LVSgfW9W3Fg
